title: TYTB
# email: takatoshiyamada.3505@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
description: is tech blog by t.yamada
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://t-yamada1008.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ty__tw
github_username:  t-yamada1008

# Build settings
theme: minima
paginate: 5

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-feed

jekyll-archives:
  enabled:
    - categories
    - tags
    - years
    - months
  layout:
    categories: archive
    tags: archive
    years: archive
    months: archive
  permalinks:
    categories: /categories/:name/
    tags: /tags/:name/
    years: /:year/
    months: /:year/:month/

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
