# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            TYTB
tagline:          'T.Yamada Tech Blog'
description:      'This is Tech Blog by T.Yamada  <a href="https://x.com/ty__tw" target="_blank">@ty__tw</a>.'
url:              https://t-yamada1008.github.io/
baseurl:          ''

author:
  name:           'T.Yamada'
  url:            https://x.com/ty__tw

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/t-yamada1008
