# _config.yml
title:            "TYTB"
tagline:          "T.Yamada Tech Blog"
description:      "This is Tech Blog by T.Yamada."
url:              "https://t-yamada1008.github.io"
baseurl:          ""  # ユーザーサイトの場合は空にする

author:
  name:           "T.Yamada"
  url:            "https://x.com/ty__tw"

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-paginate
 
paginate:         5

# Custom vars
version:          "2.1.0"

github:
  repo:           "https://github.com/t-yamada1008/t-yamada1008.github.io"
